| Category | Goal | Code | Notes |
|---|---|---|---|
| Setup | Import | `import pandas as pd` | Always `pd`, at the top |
| Create | From a list of lists | `pd.DataFrame(rows, columns=[...])` | Each inner list is one row |
| Create | From a dictionary of lists | `pd.DataFrame({"A": [1, 2], "B": [3, 4]})` | Each key is a column |
| Create | From a dictionary of dictionaries | `pd.DataFrame.from_dict(data)` | Outer keys are columns, inner keys are the index |
| Create | Outer keys as rows | `pd.DataFrame.from_dict(data, orient='index')` | Flips the table |
| Create | Set the row labels | `pd.DataFrame(rows, columns=[...], index=[...])` | |
| Create | One column | `pd.Series([30, 21], index=["Apples", "Bananas"])` | A labeled list |
| Inspect | Display | `print(df)` or `df` | In a notebook, only the last line is shown |
| Inspect | Size | `df.shape` | `(rows, columns)`, no parentheses |
| Inspect | Column names | `df.columns` | |
| Inspect | Row labels | `df.index` | |
| Inspect | Type of each column | `df.dtypes` | |
| Inspect | First rows | `df.head()` | 5 by default, `df.head(3)` for 3 |
| Inspect | Summary with missing values | `df.info()` | |
| Inspect | Statistics | `df.describe()` | Count, mean, min, max |
| Select | One column | `df["A"]` | Returns a Series |
| Select | Several columns | `df[["A", "B"]]` | Double brackets, returns a DataFrame |
| Select | Row by label | `df.loc["row1"]` | The slice end is included |
| Select | Row by position | `df.iloc[0]` | The slice end is excluded |
| Select | One cell by label | `df.loc["row1", "A"]` | Row then column |
| Select | One cell by position | `df.iloc[0, 1]` | Row then column |
| Files | Read a CSV | `pd.read_csv("file.csv")` | |
| Files | Save to CSV | `df.to_csv("file.csv", index=False)` | `index=False` skips the row labels |

| Error | Cause | Fix |
|---|---|---|
| `ValueError: Shape of passed values is (2, 1), indices imply (2, 2)` | Flat list with two column names | Wrap the values in an inner list per row |
| `SyntaxError: ':' expected after dictionary key` | Extra `{` or missing `:` | One `{` per dictionary, count them |
| `KeyError` | The column or label does not exist | Check `df.columns` or `df.index` |
| Table is flipped | Wrong `orient` or dictionary structure | Check which keys are outer and inner |


You use **`drop`**. It works on labels (the column names or the index labels).

| Goal | Code | Notes |
|---|---|---|
| Remove one column | `df.drop(columns="A")` | Clearest form |
| Remove several columns | `df.drop(columns=["A", "B"])` | List of names |
| Remove one row | `df.drop(index="row1")` | By index label |
| Remove several rows | `df.drop(index=["row1", "row2"])` | List of labels |
| Same, with `axis` | `df.drop("A", axis=1)` / `df.drop("row1", axis=0)` | `axis=1` is columns, `axis=0` is rows |
| Remove a column by position | `df.drop(columns=df.columns[0])` | Takes the name at position 0 |
| Remove a row by position | `df.drop(index=df.index[0])` | Takes the label at position 0 |

**Points to remember**

- `drop` returns a **new** DataFrame. The original is not changed, as with `reshape` in NumPy. Save the result:

```python
fruit_df = fruit_df.drop(columns="Bananas")
```

or keep the original and use a new name, such as `fruit_without_bananas_df`.

- With the default index (`0, 1, 2...`), the label of a row is its position, so `df.drop(index=0)` removes the first row.
- If the label does not exist, you get a `KeyError`. Check `df.columns` or `df.index` first.
- The `inplace=True` option modifies the original directly, but it is discouraged. Assigning the result is clearer.

**Conventions**

- Prefer `columns=` and `index=` over `axis=0` or `axis=1`. They say what you remove, so the line reads clearly.

# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [2]:
import pandas as pd

In [13]:
fruits_name = ['Apples', 'Bananas']
fruits_number = [[30, 21]]


fruit_df = pd.DataFrame(fruits_number, columns=fruits_name)


fruit_df

   Apples  Bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [20]:
data = {
    "Apples": {"2017 Sales": 35, "2018 Sales": 41}, 
    "Bananas": {"2017 Sales": 21, "2018 Sales": 34}
}

fruit_vendors =  pd.DataFrame.from_dict(data)
fruit_vendors

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [32]:
for fruit, sales in fruit_vendors.items():
    print(f"{fruit}: \n{sales}\n")

Apples:
2017 Sales    35
2018 Sales    41
Name: Apples, dtype: int64

Bananas:
2017 Sales    21
2018 Sales    34
Name: Bananas, dtype: int64

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [35]:
fruit_vendors.drop(index=fruit_vendors.index[0])

            Apples  Bananas
2018 Sales      41       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [36]:
fruit_vendors.drop(columns=fruit_vendors.columns[0])

            Bananas
2017 Sales       21
2018 Sales       34